### ISSUE TITLE
🐛: Theme Change Button Only Affects Navbar

### ISSUE THREAD

**Issue by aayank13** [aayank13/ml4e#14]
### Title

Theme Change Button Only Affects Navbar

### Bug

The **Theme Change** button in the navbar currently only changes the theme of the navbar itself, instead of applying the theme change to the entire website. This issue affects the user experience by creating an inconsistent theme across the site.

### **Steps to Reproduce**
1. Navigate to the website.
2. Click on the **Theme Change** button in the navbar.
3. Observe that only the navbar theme changes, while the rest of the site remains unchanged.

#### **Expected Behavior**
The theme change should apply to the entire website, ensuring a cohesive look across all pages and components.

#### **Actual Behavior**
Only the navbar theme changes, while the rest of the website remains in the original theme.

### **Tasks to Fix**
1. Update the theme change functionality to apply site-wide.
2. Ensure all components, including body text, backgrounds, and sections, respond to theme changes.
3. Test the functionality on multiple pages to confirm consistency.

### **Acceptance Criteria**
- The theme change button should apply the selected theme across the entire website.
- The theme remains consistent when navigating between pages.

### Full Name

Aayan

### Participant Role

Admin

**Comment by thob2112011** [comment]
Hey! I've worked on this issue and I can open a pull request for you to review right now. Should I pull it first or can you assign me to this issue?

**Comment by aayank13** [comment]
@thob2112011 I am assigning you this issue, you can send your PR now.

**Comment by thob2112011** [comment]
Hello! I'm very interested in your work. Do you currently have any task
that requires assistance, maybe related to issues I've worked on before? If
so, please open a new issue - I’d be glad to help!

Vào Th 7, 2 thg 11, 2024 vào lúc 22:22 github-actions[bot] <
***@***.***> đã viết:

**Comment by aayank13** [comment]
@thob2112011 sure!
