### ISSUE TITLE
🧑‍💻: Add Authentication Using Appwrite

### ISSUE THREAD

**Issue by aayank13** [aayank13/ml4e#17]
### **Description**  
Implement authentication functionality in the ML4E project using [Appwrite](https://appwrite.io/). This will allow users to sign up, log in, and manage their accounts securely within the platform. Authentication is crucial for enabling personalized experiences, such as saving user progress, participating in community features, and more.

---

### **Tasks**  
1. **Set up Appwrite**  
   - Install and configure Appwrite on the project server.  
   - Create the required project in the Appwrite console.  

2. **Integrate SDK**  
   - Install the Appwrite SDK in the Next.js application.  
   - Set up environment variables for Appwrite API credentials.

3. **Authentication Features**  
   - Implement sign-up functionality with email and password.  
   - Implement login functionality with email and password.  
   - Add "Forgot Password" feature using Appwrite's recovery API.

4. **Frontend UI**  
   - Design a responsive and user-friendly authentication UI.  
   - Include form validation and error handling.

5. **Protected Routes**  
   - Implement route protection to restrict access to specific pages for authenticated users only.

6. **Testing**  
   - Test authentication flow for edge cases (e.g., invalid credentials, server issues).  
   - Ensure logout functionality works seamlessly.  

---

**Resources**  
- [Appwrite Documentation](https://appwrite.io/docs)  
- [Appwrite GitHub Repository](https://github.com/appwrite/appwrite)

**Comment by wpsadi** [comment]
on it
